### PR TITLE
Bump redox users to 0.4, by proxy updates rand to 0.8

### PR DESCRIPTION
**Pull request by coolreader18**

### CODE REVIEW

**Comment by josephlr** [comment]
+1 to this, note that this is a step to update the [main rust lockfile](https://github.com/rust-lang/rust/blob/master/Cargo.lock) to only use a single version of `getrandom` and `rand`.

**Comment by soc** [comment]
Thank you!

**Comment by Xanewok** [comment]
Would it be possible to cut a new release with this change? As @josephlr mentioned, it'd help move the ecosystem off `getrandom 0.1` and friends. Thank you!

**Comment by soc** [comment]
Ok, can do that. Do you also need releases of dirs and directories, or is dirs-sys sufficient?

**Comment by josephlr** [comment]
> Ok, can do that. Do you also need releases of dirs and directories, or is dirs-sys sufficient?

Releasing `dirs-sys 0.3.5` should be sufficient

**Comment by soc** [comment]
dirs-sys 0.3.6 has been released last week!

**Pull request merged**
