### PR TITLE
Remove option-ext dependency

### PR DESCRIPTION
**Pull request by kpcyrd**
I found a way to replace the use of this dependency with a trivial compare.

### CODE REVIEW

**Comment by soc** [comment]
Sorry, but I like it the way it is.

**Comment by kpcyrd** [comment]
Why?

**Comment by AlexTMjugador** [comment]
A dependency for such a trivial operation is rather on the bloatful side, but most importantly, extends the virality of its copyleft MPL license to this MIT/Apache-licensed crate, which does not make much sense:

Cargo deny run on this crate

Can this decision be reconsidered, please?

**Comment by kpcyrd** [comment]
I noticed this PR is an exact duplicate of #24.

**Comment by soc** [comment]
> @AlexTMjugador extends the virality of its copyleft MPL license

?

**Comment by AlexTMjugador** [comment]
> > @AlexTMjugador extends the virality of its copyleft MPL license
> 
> ?

I wrote that comment before properly researching the situation with this dependency. At the moment, I have no new arguments to add to the discussion about why the dependency on `option-ext` is, in my opinion, uncomfortable. Other people have already thoroughly explained reasons I can think of in several other issues.

**Comment by nihohit** [comment]
I'd like to join the request - my org forbids the usage of crates using a copyleft license even as an indirect dependency.
@soc I understand that you prefer the code as is, I just hope that you understand that this makes `dirs-sys` and crates dependent on dirs-sys unusable by some organizations.

**Pull request closed without merging**
