### PR TITLE
redox: set user authentication to empty tuple

### PR DESCRIPTION
**Pull request by jackpot51**
This fixes compilation on Redox

### CODE REVIEW

**Comment by soc** [comment]
@jackpot51 Hi Jeremy, thanks for the PR!

To help me understand this, is this related to an earlier change in the signatures of the `redox_users` crate? If there was authentication, what kind of code would replace the goatse operator in your change?

**Comment by jackpot51** [comment]
@soc If the authentication feature is enabled, which is only required if you want to test passwords, then `redox_users::auth::Full` would be passed: https://docs.rs/redox_users/0.4.0/redox_users/auth/struct.Full.html

**Comment by soc** [comment]
@jackpot51 So `()` == `Basic`?

**Comment by jackpot51** [comment]
@soc yes, it would also be valid to use `Basic`.

**Comment by soc** [comment]
Ah, understood thanks!

**Comment by jackpot51** [comment]
Could you do a crate release with this @soc? Thanks for merging!

**Comment by soc** [comment]
@jackpot51 Merged. Do you need a new release immediately?

**Comment by soc** [comment]
Sure, will do!

**Comment by soc** [comment]
@jackpot51 I squashed your 2 commits and released 0.3.7: https://crates.io/crates/dirs-sys

Thanks!

**Comment by jackpot51** [comment]
Thank you!

**Pull request merged**
